version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "oauth_user_system.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/oauth_user_system'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A oauth_user_system.blueprints.contact.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/oauth_user_system'

volumes:
  postgres:
  redis:
